### ISSUE TITLE
Add citation information

### ISSUE THREAD

**Issue by kilodalton** [MoTrPAC/exercise-transcriptome-meta-analysis#13]
From Malene:

Citation: Amar, D., Lindholm, M.E., Norrbom, J. et al. Time trajectories in the transcriptomic response to exercise - a meta-analysis. Nat Commun 12, 3471 (2021). https://doi.org/10.1038/s41467-021-23579-x

under the introductory text on the first page as well as under the current text in the About page

Note formattting captured here:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/1878194/121487799-4f1cfd80-c987-11eb-80d2-f69ba2a7e077.png">

This is the direct link to the article:  [ https://www.nature.com/articles/s41467-021-23579-x](https://www.nature.com/articles/s41467-021-23579-x)

**Comment by jimmyzhen** [comment]
@kilodalton @malkli @david-dd-amar Please review the screenshots below and let me know your thoughts. Thanks!

![Citation_Landing_Page](https://user-images.githubusercontent.com/6956310/121733333-30faee80-caa8-11eb-9e31-72b405e74a53.png)

![Citation_About_Page](https://user-images.githubusercontent.com/6956310/121733377-43752800-caa8-11eb-821a-56e88e99b24c.png)

**Comment by jimmyzhen** [comment]
I returned to the Bay Area last night. Vacation is over and back to work 👨‍💻
