### ISSUE TITLE
Add more columns to the table in a gene's page

### ISSUE THREAD

**Issue by david-dd-amar** [MoTrPAC/exercise-transcriptome-meta-analysis#6]
We need to add the following columns:
prop_males
N
Time
yi - please call it either "Effect size" or "Beta"

**Comment by jimmyzhen** [comment]
@david-dd-amar Does the `prop_males` have a more official label for the column header? And should the "N" be used as is for the column header, or you prefer to label it as "Sample size"?

**Comment by david-dd-amar** [comment]
Sample size is better than "N"
For prop males, @jimmyzhen  maybe multiply this number by 100 and call the label "%males"?
