### ISSUE TITLE
wrong stats table at the top of the screen

### ISSUE THREAD

**Issue by david-dd-amar** [MoTrPAC/exercise-transcriptome-meta-analysis#8]
In some cases the gene's statistics are not presented as expected:
here is an example (SLC25A30):
<img width="1179" alt="Screen Shot 2021-02-04 at 9 32 00 AM" src="https://user-images.githubusercontent.com/15180422/106931995-09e07a80-66cc-11eb-92f8-ce44a67a418f.png">

**Comment by jimmyzhen** [comment]
The investigation has identified the comma-delimited `*.csv` files being the culprit. @david-dd-amar will convert and provide the gene stat files to tab-delimited `*.tsv` files as an update.
