### ISSUE TITLE
Mark cases with high I2 scores

### ISSUE THREAD

**Issue by david-dd-amar** [MoTrPAC/exercise-transcriptome-meta-analysis#9]
An idea to explore: add a title or a note below the plot in red, letting the user know that the I2 score is high, sat >70%
This is important as otherwise some users may be confused when seeing large effect sizes in the RE model

**Comment by jimmyzhen** [comment]
@david-dd-amar Is this applicable to all plots, or just the plots with high I2 scores? If the later, how can that be interpreted in the analysis input data?

Furthermore, it would be great if you can provide the exact language for the note you proposed. Thanks!

**Comment by david-dd-amar** [comment]
This is now a part of the figure title.
We mark cases with I2 between 50 and 75 with "*" and cases with I2 > 70 with "**"

We need to add some text below the plot, here is a suggestion:

* I^2 between 50% and 75% is considered to represent medium-high effect heterogeneity, p-values may be inaccurate
** I^2 > 75% is considered as to be high effect heterogeneity, p-values are likely to be inaccurate

**Comment by david-dd-amar** [comment]
Here is an example for a plot 
![ABCC11 csv forest](https://user-images.githubusercontent.com/15180422/107574034-17ea3b80-6ba3-11eb-8835-140979f467c9.png)
